variables:
  patch: $[counter('versioncounter', 100)]

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

  # We want to run `npm version` but this makes a commit so need to configure the git user first
- script: git config --global user.name "npm" && git config --global user.email "npm@npm.com" && npm version 1.0.$(patch)
  displayName: "npm version to update package version"

- script: npm install
  displayName: 'npm install'

- script: npm run build
  displayName: 'npm run build'

- script: npm test
  displayName: 'npm test'

  # Bundle deps to improve install performance
- script: |
    npm install -g bundle-deps
    bundle-deps .
  displayName: 'Bundle npm dependencies into package'

  # If we're on a PR Pack the artifact and store
- script: npm pack
  condition: eq(variables['System.PullRequest.IsFork'], 'True')
  displayName: "Package for artifact store"

- task: PublishPipelineArtifact@0
  condition: eq(variables['System.PullRequest.IsFork'], 'True')
  inputs:
    artifactName: 'armvis' 
    targetPath: ./armvis-1.0.$(patch)-prbuild

  # If we're on master publish to NPM
- task: Npm@1
  condition: and(succeeded(), eq(variables['System.PullRequest.IsFork'], 'False'), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  displayName: "Publish package to npm"
  inputs:
    command: publish
    publishEndpoint: 'npm'


