variables:
  patch: $[counter('versioncounter', 100)]

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: npm version 1.0.$(patch)
  displayName: "npm version to update package version"
  
- script: npm install
  displayName: 'npm install'


- script: npm run build
  displayName: 'npm run build'

- script: npm test
  displayName: 'npm test'

- script: |
    npm install -g bundle-deps
    bundle-deps .
  displayName: 'Bundle npm dependencies into package'


- task: Npm@1
  displayName: "Publish package to npm"
  inputs:
    command: publish
    publishEndpoint: 'npm'


